-- ================================================
-- CONFIGURACIÓN INICIAL PARA POSTGRESQL
-- ================================================
-- Este script solo crea la BASE DE DATOS.
-- Las TABLAS se crean automáticamente con TypeORM.

-- Crear la base de datos (ejecutar como superusuario)
--CREATE DATABASE backend_reservas;

-- Opcional: Crear un usuario específico para la aplicación
-- CREATE USER app_user WITH PASSWORD 'secure_password';
-- GRANT ALL PRIVILEGES ON DATABASE backend_reservas TO app_user;

-- ================================================
-- INFORMACIÓN IMPORTANTE:
-- ================================================
-- ✅ TypeORM se encarga de:
--    - Crear la tabla 'personas'
--    - Crear todas las columnas
--    - Crear índices y constraints
--    - Sincronizar cambios en las entidades
--
-- ❌ Necesitas hacer manualmente:
--    - Crear la base de datos (este script)
--    - Configurar permisos de usuario
-- ================================================

-- Una vez creada la base de datos, inicia la aplicación:
-- npm run start:dev
-- 
-- TypeORM creará automáticamente esta estructura:
--
-- TABLE personas (
--     "id_persona" SERIAL PRIMARY KEY,
--     "nombres" VARCHAR NOT NULL,
--     "paterno" VARCHAR NOT NULL, 
--     "materno" VARCHAR NOT NULL,
--     "documento_tipo" VARCHAR NOT NULL DEFAULT 'CC',
--     "documento_numero" VARCHAR NOT NULL UNIQUE,
--     "telefono" VARCHAR,
--     "telefono_verificado" BOOLEAN DEFAULT false,
--     "fecha_nacimiento" DATE,
--     "genero" VARCHAR,
--     "url_foto" TEXT,
--     "creado_en" TIMESTAMP DEFAULT now(),
--     "actualizado_en" TIMESTAMP DEFAULT now()
-- );